### ISSUE TITLE
Кнопаньке «Показать ещё» очень одиноко

### ISSUE THREAD

**Issue by blond** [tavriaforever/bem-forum-tests#175]
![2014-07-28 18 04 35](https://cloud.githubusercontent.com/assets/2225579/3721479/edffc338-1660-11e4-80dc-ed22dafbd87e.png)

**Comment by tavriaforever** [comment]
Изображение растолстело - поправили

**Comment by blond** [comment]
Надо как-то сворачивать такие картинки =)
