### ISSUE TITLE
Не работает сочетание `cmd + A` на инпутах

### ISSUE THREAD

**Issue by blond** [tavriaforever/bem-forum-tests#176]

**Comment by just-boris** [comment]
а еще `cmd+enter` для отправки

**Comment by just-boris** [comment]
Эй, а почему мне сочетание клавиш отформатировало, а комментатору выше  -- нет?

**Comment by tavriaforever** [comment]
cmd+enter принято

**Comment by blond** [comment]
`cmd + a` заработало.

@just-boris, наверное, потому что это коммент, а выше заголовок.

**Comment by belyanskii** [comment]
123
